#!/bin/bash
#
# Startup script for WebLogic NodeManager
#
# chkconfig: 345 95 16
# description: WebLogic NodeManager startup script
# to enable on bootup on redhat "chkconfig --level 35 wlsnm on"

WLS_USER=oracle
WL_HOME=/home/oracle/Oracle/Middleware/wlserver_10.3
WLST=/home/oracle/Oracle/Middleware/wlserver_10.3/common/bin/wlst.sh
SCRIPT=/home/oracle/add.py

case "$1" in
start)
exec su - -p --shell=/bin/sh $WLS_USER -c "$WLST $SCRIPT start"
echo "Registering to the cluster"
;;
stop)
exec su - -p --shell=/bin/sh $WLS_USER -c "$WLST $SCRIPT stop"
echo "Deregistering from the cluster"
;;
*)
echo "Usage: $0 {start|stop}"
exit 1
esac

exit $?
